[workspace]
members = [
  "packages/desmos-std",
  "packages/proto-compiler",
  "packages/desmos-proto",
  "contracts/dtag-auctioneer",
  "contracts/filter-posts",
  "contracts/dummy-tokenomics"
]

[profile.release.package.desmos]
codegen-units = 1
incremental = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
