[workspace]
members = [
    "contracts/*"
]

[workspace.dependencies]
# Cosmwasm related dependencies
cosmwasm-std = "1.2.7"
cosmwasm-storage = "1.2.7"
cosmwasm-schema = "1.2.7"
cw-storage-plus = "1.1.0"
cw-utils = "1.0.1"
cw2 = "1.1.0"
cw-multi-test = "0.16.5"
# Desmos dependencies
desmos-bindings = { version = "1.1.1", default-features = false }
# Misc dependencies
schemars = "0.8.12"
serde = { version = "1.0.166", default-features = false }
thiserror = "1.0.41"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
