[package]
name = "desmos-std"
version = "0.1.0"
authors = ["Leonardo Bragagnolo <leonardo@forbole.com>", "Paul Chen <paul@forbole.com>"]
edition = "2018"
description = "Desmos network standards for smart contracts development"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-contracts"
homepage = "https://www.desmos.network"
keywords = ["social-networks", "blockchain", "smart-contracts", "desmos", "cryptocurrency"]

[dependencies]
cosmwasm-std = { version = "1.0.0-beta5" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta" }

[features]
profiles = []
subspaces = []
relationships = []
