[package]
name = "proto-compiler"
version = "0.0.1"
authors = ["bragaz <leo.braga95@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-contracts"
homepage = "https://www.desmos.network"
keywords = ["social-network", "blockchain", "smart-contracts"]

[dependencies]
bytes = { version = "1", default-features = false }
prost = { version = "0.9.0" }

[build-dependencies]
prost-build = { version = "0.9.0" }
