[package]
name = "desmos-cw"
version = "0.1.4"
authors = ["Leonardo Bragagnolo <leonardo@forbole.com>"]
edition = "2018"
description = "Desmos network utilities for smart contracts development"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-contracts"
homepage = "https://www.desmos.network"
keywords = ["social-network", "blockchain", "smart-contracts"]

[dependencies]
cosmwasm-std = { version = "1.0.0-beta" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta" }
