[package]
name = "desmos-proto"
version = "0.0.1"
authors = ["Leonardo Bragagnolo <leonardo@forbole.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/desmos-labs/desmos-contracts"
homepage = "https://www.desmos.network"
keywords = ["social-network", "blockchain", "smart-contracts"]

[dependencies]
prost = { version = "0.9" }
prost-types = { version = "0.9"}
